### ISSUE TITLE
Is new4j-rdflib is available for free instances of aura? Since we are using oauth we dont have any password to provide as credential.

### ISSUE THREAD

**Issue by MehranDHN** [neo4j-labs/rdflib-neo4j#38]

**Comment by nmervaillie** [comment]
Hi

Yes, rdflib-neo4j is compatible with Aura.

SSO compatibility is available since version 1.1 (docs are no published yet but should be soon). You just need to build a neo4j driver as described here https://neo4j.com/docs/python-manual/current/connect-advanced/#_bearer_authentication
and pass it when initializing the store
